# When a tagged commit is pushed the documentation pages and npm module are published/deployed:
os: linux
# linux dist that includes C++ compiler needed for native node modules
dist: bionic
# npm version patch -m "%s Release"
language: node_js
node_js:
  - "lts/*"
#services:
#  - mysql
#  - postgresql
env:
  - REPO_VER=v1.5.5 MYSQL_MAJOR=8 MYSQL_MINOR=14 MYSQL_PATCH=1 MYSQL_ODBC_MAJOR=8 MYSQL_ODBC_MINOR=0 MYSQL_ODBC_PATCH=19 MYSQL_ODBC_DATASOURCE=MySQL POSTGRESQL_MAJOR=12 POSTGRESQL_ODBC_DATASOURCE=PostgreSQL MSSQL_VER=2019 MSSQL_SA_PWD=sqlS3rv35local MSSQL_PWD=390Khy7MxeU8N MSSQL_ODBC_DATASOURCE=SqlServer
before_install:
  - sudo apt-get install unixodbc unixodbc-dev
  - wget -O install-mssql.sh https://raw.githubusercontent.com/ugate/repo/$REPO_VER/mssql/install.sh
  - wget -O install-mysql.sh https://raw.githubusercontent.com/ugate/repo/$REPO_VER/mysql/install.sh
  - wget -O install-mysql-odbc.sh https://raw.githubusercontent.com/ugate/repo/$REPO_VER/mysql/install-odbc.sh
  - wget -O install-postgresql.sh https://raw.githubusercontent.com/ugate/repo/$REPO_VER/postgresql/install.sh
  - wget -O install-postgresql-odbc.sh https://raw.githubusercontent.com/ugate/repo/$REPO_VER/postgresql/install-odbc.sh
  - bash ./install-mssql.sh
  - bash ./install-mysql.sh
  - bash ./install-mysql-odbc.sh
  - bash ./install-postgresql.sh
  - bash ./install-postgresql-odbc.sh
  - rm -rf install-mssql.sh
  - rm -rf install-mysql.sh
  - rm -rf install-mysql-odbc.sh
  - rm -rf install-postgresql.sh
  - rm -rf install-postgresql-odbc.sh
  - odbcinst -j
  - odbcinst -q -d
  - odbcinst -q -s
branches:
  only:
    - master
    - "/v*/"
script:
# - printenv
  - "npm run test-postgresql"
  - "npm run test-mssql"
  - "lab -v -P .test -c -t 85 -e prod"
deploy:
  #edge: true # avoid dpl v2 missing api_token
  - provider: script
    skip_cleanup: true # deprecated, use cleanup with new dpl ver
    cleanup: false
    script: npm run jsdocp-deploy
    on:
      tags: true # only on tagging commit
      branch:
        - /v(\d+\.)?(\d+\.)?(\*|\d+)$/
  - provider: npm
    skip_cleanup: false # deprecated, use cleanup with new dpl ver
    cleanup: true
    email: "ugate.public@gmail.com"
    api_token: $NPM_TOKEN  # Set in the settings page of your repository, as a secure variable
    on:
      tags: true # only on tagging commit
      branch:
        - /v(\d+\.)?(\d+\.)?(\*|\d+)$/