# When a tagged commit is pushed the documentation pages and npm module are published/deployed:
os: linux
# linux dist that includes C++ compiler needed for native node modules
dist: bionic
# npm version patch -m "%s Release"
language: node_js
node_js:
  - "lts/*"
#services:
#  - mysql
#  - postgresql
env:
  - MYSQL_MAJOR=8 MYSQL_MINOR=14 MYSQL_PATCH=1 MYSQL_ODBC_MAJOR=8 MYSQL_ODBC_MINOR=0 MYSQL_ODBC_PATCH=19 MYSQL_ODBC_DATASOURCE=MySQL POSTGRESQL_MAJOR=12 POSTGRESQL_ODBC_DATASOURCE=PostgreSQL
before_install:
  - sudo apt-get install unixodbc unixodbc-dev
  - bash ./test/fixtures/mysql/install.sh
  - bash ./test/fixtures/mysql/install-odbc.sh
  - bash ./test/fixtures/postgresql/install.sh
  - bash ./test/fixtures/postgresql/install-odbc.sh
  - odbcinst -j
  - odbcinst -q -d
  - odbcinst -q -s
branches:
  only:
    - master
    - "/v*/"
script:
# - printenv
  - "npm test"
  - "npm run test-postgresql"
deploy:
  #edge: true # avoid dpl v2 missing api_token
  - provider: script
    cleanup: true
    script: npm run jsdocp-deploy
    on:
      tags: true # only on tagging commit
      branch:
        - /v(\d+\.)?(\d+\.)?(\*|\d+)$/
  - provider: npm
    email: "ugate.public@gmail.com"
    api_token: $NPM_TOKEN  # Set in the settings page of your repository, as a secure variable
    on:
      tags: true # only on tagging commit
      branch:
        - /v(\d+\.)?(\d+\.)?(\*|\d+)$/