# When a tagged commit is pushed the documentation pages and npm module are published/deployed:
os: linux
# linux dist that includes C++ compiler needed for native node modules
dist: xenial
# npm version patch -m "%s Release"
language: node_js
node_js:
  - "lts/*"
services:
  - mysql
  - postgresql
branches:
  only:
    - master
    - "/v*/"
script:
# - printenv
  - "npm test"
deploy:
  #edge: true # avoid dpl v2 missing api_token
  - provider: script
    cleanup: true
    script: npm run jsdocp-deploy
    on:
      tags: true # only on tagging commit
      branch:
        - /v(\d+\.)?(\d+\.)?(\*|\d+)$/
  - provider: npm
    email: "ugate.public@gmail.com"
    api_token: $NPM_TOKEN  # Set in the settings page of your repository, as a secure variable
    on:
      tags: true # only on tagging commit
      branch:
        - /v(\d+\.)?(\d+\.)?(\*|\d+)$/